name: "run unit tests on github actions"

on:
  push:
    branches:
      - "main"
    pull_request:
      branches:
        - "*"

jobs:
  checks:
    name: checks
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10
      - name: "install"
        run: pip install .[dev]
      - name: "mypy"
        run: make test_mypy
      - name: "flake8"
        run: make test_flake8

  run_tests:
    name: ${{ matrix.os }} with Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: ["3.7", "3.10"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
        name: "setup python"
      - name: "install"
        run: |
          pip install .[dev]
      - name: "run tests"
        run: |
          make test_coverage
